name: Pre-merge checks

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    build_custom_detekt_rules:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Assemble app
          run: ./gradlew app:assemble

  build_custom_detekt_rules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build detekt rules
        run: ./gradlew detekt-rules:build

  test_custom_detekt_rules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test detekt rules
        run: ./gradlew detekt-rules:test